### ISSUE TITLE
Add effects from SilentRuin module

### ISSUE THREAD

**Issue by BeeGrinder** [BeeGrinder/FantasyGrounds-SW5e#17]
Create class specific features and effects similar to how it is in rob2e's add-on.
Berserker: Rage: saving throw, Rage: Mele bonus. Unarmored Defense. Reckless. Danger Sense immunities

**Comment by lordcygnus** [comment]
Hey! about the classes features, I'm using these files as reference for each one of the related skills between versions, since the SW5E bases most of the features from DnD5E, maybe they can be useful if are available as such once you level up the character and gain the appropriate feature. Check the files, and let me know if this can be implemented and if you need any more information as well.
[Clases Features Examples.zip](https://github.com/BeeGrinder/FantasyGrounds-SW5e/files/5618300/Clases.Features.Examples.zip)

**Comment by BeeGrinder** [comment]
Yes, excellent point.  In all my work I spend a LOT of time trying to figure out what the sw5e thing is reflavored from in "real" 5e.  I just had a bug and figuring out "Dark Sense" was just reflavored Augery took me a while.

So, if you could do me a great favor and list the sw5e class/feature followed by the "real" 5e class/feature and my work will be much faster.

**Comment by BeeGrinder** [comment]
SilentRuin has created an extensive list of effects for the effect button.  This can be easily added to the base PHB module.

**Comment by BeeGrinder** [comment]
Done in commit c88f66cc28331dcf890231668ee33557174c35bf
